const PDFDocument = require("pdfkit");

// Helper: draw a bold coloured section heading with a blue underline
function drawSection(doc, title) {
  doc.fillColor("#0B1120").font("Helvetica-Bold").fontSize(13).text(title);
  const lineY = doc.y + 2;
  doc
    .moveTo(50, lineY)
    .lineTo(doc.page.width - 50, lineY)
    .strokeColor("#4A9EFF")
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.6);
  doc.fillColor("#222222").font("Helvetica").fontSize(11);
}

// Helper: draw a label: value row
function drawField(doc, label, value) {
  doc.font("Helvetica-Bold").fillColor("#555555").text(label + ": ", { continued: true });
  doc.font("Helvetica").fillColor("#111111").text(String(value || "N/A"));
}

function fmtDate(dateStr) {
  if (!dateStr) return "N/A";
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// Returns a Buffer containing the professional lease agreement PDF
function generateLeasePDF(lease, tenant, property) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width;

    // Dark navy header bar
    doc.rect(0, 0, pageW, 80).fill("#0B1120");
    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("PropMate AI", 50, 22, { width: pageW - 100 });
    doc
      .font("Helvetica")
      .fontSize(11)
      .text("Lease Agreement", 50, 50);

    doc.moveDown(3.5);
    doc.fillColor("#0B1120");

    // Property Details
    drawSection(doc, "Property Details");
    drawField(doc, "Property Name", property.title);
    drawField(doc, "Location", property.location);
    const fullAddress = [property.address, property.city, property.country]
      .filter(Boolean)
      .join(", ");
    drawField(doc, "Address", fullAddress || "N/A");
    doc.moveDown(0.8);

    // Tenant Information
    drawSection(doc, "Tenant Information");
    drawField(doc, "Full Name", tenant.name);
    drawField(doc, "Email", tenant.email);
    drawField(doc, "Phone", tenant.phone || "N/A");
    doc.moveDown(0.8);

    // Lease Terms
    drawSection(doc, "Lease Terms");
    drawField(doc, "Start Date", fmtDate(lease.startDate));
    drawField(doc, "End Date", fmtDate(lease.endDate));
    drawField(
      doc,
      "Status",
      lease.status
        ? lease.status.charAt(0).toUpperCase() + lease.status.slice(1)
        : "N/A",
    );
    if (lease.notes) drawField(doc, "Notes", lease.notes);
    doc.moveDown(0.8);

    // Monthly Rent
    drawSection(doc, "Monthly Rent");
    drawField(
      doc,
      "Rent Amount",
      (lease.currency || "USD") + " " + Number(lease.rentAmount).toLocaleString() + " / month",
    );
    doc.moveDown(2);

    // Signatures block
    drawSection(doc, "Signatures");
    doc.moveDown(1);
    const sigY = doc.y + 40;
    const col2 = pageW / 2 + 20;
    doc
      .moveTo(50, sigY)
      .lineTo(250, sigY)
      .strokeColor("#aaaaaa")
      .lineWidth(1)
      .stroke();
    doc
      .moveTo(col2, sigY)
      .lineTo(col2 + 200, sigY)
      .strokeColor("#aaaaaa")
      .stroke();
    doc
      .fillColor("#777777")
      .font("Helvetica")
      .fontSize(10)
      .text("Landlord Signature", 50, sigY + 6, { width: 200 });
    doc.text("Tenant Signature", col2, sigY + 6, { width: 200 });

    // Footer
    doc
      .fillColor("#aaaaaa")
      .fontSize(9)
      .text(
        "Generated by PropMate AI \xB7 propmateai.com",
        50,
        doc.page.height - 50,
        { width: pageW - 100, align: "center" },
      );

    doc.end();
  });
}

// Returns a Buffer containing a rent receipt PDF with a PAID stamp
function generateRentReceiptPDF(payment, tenant, property) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageW = doc.page.width;
    const pageH = doc.page.height;
    const receiptNumber = "RCPT-" + Date.now();

    // Dark navy header bar
    doc.rect(0, 0, pageW, 80).fill("#0B1120");
    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("PropMate AI", 50, 22, { width: pageW - 100 });
    doc.font("Helvetica").fontSize(11).text("Rent Receipt", 50, 50);

    doc.moveDown(3.5);
    doc.fillColor("#0B1120");

    // Receipt meta
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .fillColor("#0B1120")
      .text("Receipt No: " + receiptNumber);
    doc
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#666666")
      .text("Issued: " + fmtDate(new Date()));
    doc.moveDown(1);

    // Tenant
    drawSection(doc, "Tenant");
    drawField(doc, "Name", tenant.name);
    drawField(doc, "Email", tenant.email);
    doc.moveDown(0.8);

    // Property
    drawSection(doc, "Property");
    drawField(doc, "Name", property.title);
    drawField(doc, "Location", property.location);
    doc.moveDown(0.8);

    // Payment Details
    drawSection(doc, "Payment Details");
    drawField(
      doc,
      "Amount Paid",
      (payment.currency || "USD") + " " + Number(payment.amount).toLocaleString(),
    );
    drawField(doc, "Payment Method", payment.paymentMethod || "Bank Transfer");
    drawField(
      doc,
      "Period Covered",
      fmtDate(payment.periodStart) + " – " + fmtDate(payment.periodEnd),
    );

    // Large diagonal PAID stamp
    doc.save();
    doc.rotate(-35, { origin: [pageW / 2, pageH / 2] });
    doc
      .fontSize(100)
      .fillColor("#16a34a")
      .opacity(0.13)
      .text("PAID", 0, pageH / 2 - 55, { width: pageW, align: "center" });
    doc.restore();

    // Footer
    doc
      .fillColor("#aaaaaa")
      .opacity(1)
      .fontSize(9)
      .text(
        "Generated by PropMate AI \xB7 propmateai.com",
        50,
        pageH - 50,
        { width: pageW - 100, align: "center" },
      );

    doc.end();
  });
}

module.exports = { generateLeasePDF, generateRentReceiptPDF };
